### ISSUE TITLE
Waf process

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#102]
Please add to your waf process that the documentation is also build using make html for the readthedocs and make latexpdf for my review with a printed pdf version. I have some problems compiling, so this might be associated with a little setup cost initially ...

**Comment by benediktkauf** [comment]
I have included the latexpdf in the waf process so it should be working when you run the whole thing. However, I wasn't able to get the make latexpdf command working. Could you maybe attach the error message you get when only running make latexpdf?

**Comment by peisenha** [comment]
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/hypcap.sty)
Writing index file grmpy.idx
(./grmpy.aux) (/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd)
(/usr/share/texlive/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./grmpy.out) (./grmpy.out)
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1phv.fd)<<ot1.cmap>><<oml.cmap
>><<oms.cmap>><<omx.cmap>>
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd) [1{/var/lib/texmf/fo
nts/map/pdftex/updmap/pdftex.map}] [2] (./grmpy.toc) [1] [2]
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)

LaTeX Warning: Hyper reference `bibliography:hecvyr05' on page 1 undefined on i
nput line 73.


! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.83 ...svg/maxAge=2592000:target:/apistatus}.svg}

**Comment by benediktkauf** [comment]
I have set the svg images to htmlonly. Does it work now?

**Comment by peisenha** [comment]
No. Please set up a proper workflow somewhere https://www.tecmint.com/install-ubuntu-16-04-alongside-with-windows-10-or-8-in-dual-boot/ If you do not or want to do this, then please set up a computer at IAME. @SeBecker can help with the setup of ubuntu

**Comment by peisenha** [comment]
This issue seems to be specific to my computer after all, I will try to fix it directly.

**Comment by peisenha** [comment]
As it turns out, the error only occurs with sphinx version 1.6.x so I downgraded to 1.5
