### ISSUE TITLE
turn of FutureWarnings

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#109]
/home/peisenha/.envs/policyMetrics/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

**Comment by SeBecker** [comment]
I added the following code snippet in front of the import pandas command in simulate_auxiliary.py:
`import warnings`
`warnings.simplefilter(action='ignore', category=FutureWarning)
`
