### ISSUE TITLE
code coveraget to more than 95%

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#115]
We just need to add an integration test that raises a UserError ... https://codecov.io/gh/grmToolbox/grmpy/src/master/grmpy/check/custom_exceptions.py This file's coverage is the main culprit.

**Comment by peisenha** [comment]
This is also easily added as an integration test: https://codecov.io/gh/grmToolbox/grmpy/src/master/grmpy/__init__.py by just calling grmpy.test() test explicitly

**Comment by SeBecker** [comment]
I added a test to test_integration.py that checks if a UserError is raised when one tries to estimate a deterministic init file with the initialization file values as start values.

**Comment by SeBecker** [comment]
Further on i added an unit test that ensures that the read process provides the same type lists for the TREATED and UNTREATED section, if i set add a binary flag to different variables in both sections. Additionally the test includes a small snippet that checks that it is not possible to add binary flags to intercept coefficients.

**Comment by SeBecker** [comment]
sebecker_bugfixes is above 95%.
https://codecov.io/gh/grmToolbox/grmpy/branch/sebecker_bugfixes
