### ISSUE TITLE
MTE Information 

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#12]
Please add the calculation of the MTE based on https://www.aeaweb.org/articles?id=10.1257/aer.101.6.2754 to our information file.

- [x] Unit test for special case that MTE is flat ....

**Comment by peisenha** [comment]
Please include this in the information file, 0.01, 0.05, 0.10, ...., 0.95, 0.99. Unit test, the MTE needs to be flat if difference in covariances is zero.

**Comment by SeBecker** [comment]
Do you have any preferences regarding the implementation layout?

**Comment by peisenha** [comment]
.. regarding the layout, see comment to #16 . I added a task list to the issue description.
