### ISSUE TITLE
bumpversion

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#14]
https://github.com/peritus/bumpversion To ease workflow with pypi releases

**Comment by peisenha** [comment]
.... also see Tobias's slack message in #grmpy

**Comment by tobiasraabe** [comment]
Hey, just saw two more programs which are still supported and seem promising to overcome this problem and a lot more:
- https://github.com/zestsoftware/zest.releaser
- https://github.com/ofek/hatch

**Comment by peisenha** [comment]
I added the alternative tools to our TODO List in the docs. We will revisit this once we actually are in the process of releasing to pypi regularly.

**Comment by peisenha** [comment]
I want our Issue Tracker to only contain tasks that we will be acting shortly. Thus, this is example where the TODO list in the docs suffices..
