### ISSUE TITLE
Some comments on test_unit.py

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#22]
- Please refactor 
```
            for f in glob.glob("*.grmpy.*"):
                os.remove(f)
```
into a function new function cleanup(). This shows up numerous times in the test-related modules
- Please do not use assert np.array_equal instead use np.testing.assert_equal instead, try to avoid using assert ... altogether in the test modules.

- This could use a loop:
`            assert np.array_equal(df.Y[df.D == 1], df.Y1[df.D == 1])`
`            assert np.array_equal(df.Y[df.D == 0], df.Y1[df.D == 0])`

- Please consider replacing this `            x_ = [col for col in df if col.startswith('X')]` by using  http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.filter.html
- There is a print statement in test5()
- Why do we have test_1 and test_2 separate, they are pretty much identical? It is enough if the is_deterministic flag is tested with probablity 0.1

Talk to you next week ...

**Comment by SeBecker** [comment]
> Why do we have test_1 and test_2 separate, they are pretty much identical? It is enough if the is_deterministic flag is tested with probablity 0.1

In my version the probability is set  to 1.0 (test2) or what are you referring to? The idea was to test the relationships in general and in the deterministic case separately.  But you are right, maybe it would be better to merge the tests and loop over the different case specifications.

**Comment by peisenha** [comment]
I understand, please merge both.
