### ISSUE TITLE
Order of information for covariance matrix

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#31]
This does not have anything to do with the order that you specified in the documentation, right?

```
    U0_sd, U1_sd, V_sd = init_dict['DIST']['all'][:3]
    vars_ = [U0_sd ** 2, U1_sd ** 2, V_sd ** 2]
    U01, U0_V, U1_V = init_dict['DIST']['all'][3:]
    covar_ = [U01 ** 2, U0_V ** 2, U1_V ** 2]
    Dist_coeffs = init_dict['DIST']['all']
```
If so, please align the code with the documentation.

**Comment by SeBecker** [comment]
I have fixed the code such that it corresponds to the documentation.

`    U0_sd, U1_sd, V_sd = init_dict['DIST']['all'][0], init_dict['DIST']['all'][3],\
                         init_dict['DIST']['all'][5]
    vars_ = [U0_sd ** 2, U1_sd ** 2, V_sd ** 2]
    U01, U0_V, U1_V = init_dict['DIST']['all'][1], init_dict['DIST']['all'][2], \
                      init_dict['DIST']['all'][4]
`

`    dict_['DIST']['coeff'] = []
    dict_['DIST']['coeff'].append(b[0, 0] ** 0.5)
    dict_['DIST']['coeff'].append(b[0, 1])
    dict_['DIST']['coeff'].append(b[0, 2])
    dict_['DIST']['coeff'].append(b[1, 1] ** 0.5)
    dict_['DIST']['coeff'].append(b[2, 1])
    dict_['DIST']['coeff'].append(b[2, 2] ** 0.5)
`
