### ISSUE TITLE
NUMPY Criterion

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#40]
Please implement version of the likelihood function that relies on NUMPY and avoids the time consuming loop. As a suggestions, set up a unit test that compares your slow version against a fast version for random initialization files.

**Comment by SeBecker** [comment]
I updated the likelihood function in estimate_auxiliary.py. I works much faster now, but I am not sure if it comes up with your expectations. Let me know what you think of it.

**Comment by peisenha** [comment]
Looks very good from a performance point of view. If you also added a unit tests for the two implementations, then go ahead and close this issue for now.
