### ISSUE TITLE
Update Regression Tests

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#42]
Please include in our regression test a single evaluation of the criterion function at the starting values in addition to the overall statistic on the simulated dataset.

**Comment by SeBecker** [comment]
Does Criterion function mean the likelihood function, an estimation with 1 evaluation or anything else?
If one of the mentioned options is appropriate, there would be the problem that our battery generates dictionaries that are deterministic with probability 0.1. That means that for both options the function would fail to provide neither the log likelihood value nor an estimation (zero division error ...). An easy solution would be to constrain the generating process in the whole loop. 
But maybe my i am wrong regarding my starting point, so please let me know what you mean by 'single evaluation of the criterion function'.

**Comment by peisenha** [comment]
Please only create non-deterministic regression tests so we can avoid the case distinction
`     if 0.00 in dict_['DIST']['coeff']:
            stat = np.sum(df.sum())
            tests += [(stat, dict_)]
        else:
            stat = np.sum(df.sum())`

Also, isn't the if statement too restrictive. How about zero covariances?
