### ISSUE TITLE
MTE Caclulation flawed

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#55]
MTE is flat, but has wrong level.
[init.txt](https://github.com/grmToolbox/grmpy/files/1351504/init.txt)
[simulatio_info.txt](https://github.com/grmToolbox/grmpy/files/1351505/simulatio_info.txt)

**Comment by SeBecker** [comment]
I reopened th se_bugfixes branch and fixed the bug. It should work now.
