### ISSUE TITLE
Renaming samples

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#65]
In the relevant output files, please adopt the following naming convention. The sample that is constructed by the researchers is the Observed Sample instead of the Sample and the others are the Simulated Sample either at the start or end see #64 ....

Also, please change the layout of the descriptives.respy.info so that you do not report all the desribtives by sample by instead like this. This allows for easier inspection of the model fit as the relevant information is grouped together.

  All
Observed Sample                               
Simulated Sample (at finish)             
Simulated Sample (at start)

  Treated
Observed Sample                               
Simulated Sample (at finish)             
Simulated Sample (at start)

  Untreated
Observed Sample                               
Simulated Sample (at finish)             
Simulated Sample (at start)

**Comment by SeBecker** [comment]
Done.
[descriptives.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1368023/descriptives.grmpy.txt)
