### ISSUE TITLE
Option for Starting values

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#66]
Please move the option for starting values into the initialization file in the ESTIMATION block with the flag start

ESTIMATION
        agents                      406
        file                      B582A518.grmpy.txt
        optimizer  ...
       start     init or auto as the two options

**Comment by peisenha** [comment]
The only argument to be passed in any function that the conventional user knows about needs to be the filename for the initialization file.

**Comment by SeBecker** [comment]
The starting value option is part of the init file from now on.
