### ISSUE TITLE
Simulated Samples at start and finish

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#70]
I was unclear about what exactly I wanted earlier, I apologize. Please modify the already quite nice setup in the following way:

- I for these two simulation, please do not simulate the observable covariates (X,Z) but instead read them in from the observed sample. This ensures that in the research case, somebody coming with an externally prepared dataset, the model fit statistics are still informative. This will probably require some thinking on how to still ensure that test_integration_test_3 is still working as you need to align the unobservables in this case. 

If this is unclear, please add this issue to our meeting agenda tomorrow.

**Comment by SeBecker** [comment]
I adjusted the estimation process accordingly. #71 should be fixed as well.
