### ISSUE TITLE
Observed and Simulated Sample at Start

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#71]
Maybe there is a good reason, but why are the simulated (at start) and observed samples not 100% identical when using the same initialization file to simulate a sample and start an estimation?

[est.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1368448/est.grmpy.txt)
[notes.txt](https://github.com/grmToolbox/grmpy/files/1368449/notes.txt)
[test.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1368450/test.grmpy.txt)

**Comment by SeBecker** [comment]
closed see #70.
