### ISSUE TITLE
Value of Criterion Function at truth

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#73]
Please add the information about the value of the criterion function at the truth to the information on simulated datasets in `*.grmpy.info`

**Comment by peisenha** [comment]
Any update?

**Comment by peisenha** [comment]
Please tackle this so we can reduce our backlog ...

**Comment by SeBecker** [comment]
I integrated the criteria function value to the output file.
[172354A7.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1547585/172354A7.grmpy.txt)
