### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#74]
- Allow direct import of estimate from grmpy package such as `from grmpy import estimate` by adding `from grmpy.estimate.estimate import estimate` to the package `__init__.py`
- Please remove apparently unused and flawed function `def simulate_outcomes_estimation(init_dict, X, Z):`,. Use this as a reminder to check and remove all ununsed function.... I activated codacy also for the branches now. Also Pycharm allows to use their integrated code review tool. Otherwise https://www.codacy.com/app/eisenhauer/grmpy/dashboard?bid=5343759
- Check code for unused function arguments such as here `def adjust_output(opt_rslt, init_dict, start_values, optimizer, dict_=None):
`
- Please change the flag values for start in the initialization file to auto and init not init_values

**Comment by SeBecker** [comment]
I changed the flag, included the import in __init__.py and started to clean the code.

**Comment by peisenha** [comment]
Any update?

**Comment by peisenha** [comment]
Can we close this?

**Comment by SeBecker** [comment]
This is done.
