### ISSUE TITLE
BFGS Return

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#75]
Here is an example, simulate with simulate.grmpy.ini and then start the estimation with estimate.grmpy.ini ...
Just following each evaluation of the crtiterion function shows that the lowest points visited results in roughly 3.22 criterion, but 5.56 is printed in est.grmpy.log

[estimate.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1369166/estimate.grmpy.txt)
[simulate.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1369167/simulate.grmpy.txt)
[est.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1369168/est.grmpy.txt)

**Comment by SeBecker** [comment]
I fixed the adjustment process so that it will always return the evaluation with the lowest criteria function value as long as this value is smaller than the criteria function value at the start.
