### ISSUE TITLE
MAXITER = 0 as Special Case 

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#76]
When setting maxiter to zero for either optimizer I get the following message. Please add an explicit regression tests which runs this special case.

[test.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1390019/test.grmpy.txt)

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    grmpy.estimate('test.grmpy.ini')
  File "../../grmpy/estimate/estimate.py", line 47, in estimate
    print_logfile(dict_, rslt)
  File "../../grmpy/estimate/estimate_auxiliary.py", line 217, in print_logfile
    file_.write(fmt.format('', section + ':', rslt[section.lower()]))
KeyError: 'warning'

**Comment by peisenha** [comment]
Are there any problems in adressing this issue or did you just not get to it yet? Let me know if you need any help ...

**Comment by SeBecker** [comment]
I added a test in test_integration.py.
