### ISSUE TITLE
MAXITER = 0 Parameters

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#78]
I want a simple evaluation of the criterion function at the truth. Why are the economic parameters (starting with identifier 14) different?

[est.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1390034/est.grmpy.txt)
[test.grmpy.txt](https://github.com/grmToolbox/grmpy/files/1390035/test.grmpy.txt)

**Comment by SeBecker** [comment]
I adjusted the estimation process appropriately.
