### ISSUE TITLE
PYTEST Fixtures

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#81]
We set up two fixtures in conftest.py. However, they are not called @pytest.mark.usefixtures('fresh_directory', 'set_seed') is missing for our test classes. See here for the doc https://docs.pytest.org/en/latest/fixture.html and here for use in respy https://github.com/restudToolbox/package/blob/master/respy/tests/test_integration.py, line 19

Otherwise, we do not have full reproducibilty as the seeds might be different.

**Comment by SeBecker** [comment]
I added the calls to our test files.
