### ISSUE TITLE
Failures of automatic starting values

### ISSUE THREAD

**Issue by peisenha** [grmToolbox/grmpy#83]
We provide the user with the option to use automatic starting values. In the case of a model where most/all agents are in the same state this breaks down. An OLS estimation by treatment status is not possible and the PROBIT for the choice equation is likely to result in a PerfectSeparation error. This is a problem in our test setup, where we want to run the property test battery for hours and every failure needs to point at a bug and not just bad luck with the random simulated sample 

Please do the following:
- Capture any error in the automatic creation of starting values and, in the case where this occurs, default back to the parameters in the initialization file.
- Add a warning message to est.grmpy.log ...

Best, Philipp

**Comment by peisenha** [comment]
Any updates here?

**Comment by SeBecker** [comment]
From now on the estimation process uses the init file values as start values if there is a perfect separation or a value error because of a low number of treated or untreated individuals. Moreover the process includes a warning message to the estimation output file.
